export const DISCLAIMER_ACCEPTED = 'DISCLAIMER_ACCEPTED';
export const TOKEN = 'TOKEN';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const SOMETHING_WRONG = 'SOMETHING_WRONG';
export const MANDATORY_FIELDS_EMPTY = 'MANDATORY_FIELDS_EMPTY';